# Generated by Django 4.1.7 on 2023-04-05 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='updated',
        ),
        migrations.AlterField(
            model_name='expense',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='journey_destination',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Thika', 'Thika'), ('Malaa', 'Malaa'), ('Makongeni', 'Makongeni')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='journey_start',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Thika', 'Thika'), ('Malaa', 'Malaa'), ('Makongeni', 'Makongeni')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
