# Generated by Django 4.1.7 on 2023-04-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0003_expense_created_by_trip_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_by',
        ),
    ]
