# Generated by Django 4.1.7 on 2023-04-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0004_remove_trip_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
    ]
