# Generated by Django 4.1.7 on 2023-04-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0006_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
