# Generated by Django 4.2.2 on 2023-06-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0020_alter_expense_status_alter_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Pending', max_length=100),
        ),
    ]
